name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🔧 Install dependencies
        run: npm ci

      - name: 🔨 Build Next.js site
        run: npm run build

      - name: 🚀 Install Firebase CLI
        run: npm install -g firebase-tools

      - name: 🔐 Firebase Deploy
        run: firebase deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}"
